---
title: "load_data"
author: "TB"
date: "5/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library('magrittr')
# load cytominer 

```

# Load tracked data and assess the quality
```{r}
# define file name and result folder for tracked experiments
csv_file_name <- 'tracks.csv'
dir_list <- list('../../analysis/2017_05_10_neutrophils_cp17_sp17/',
                 '../../analysis/2017_05_10_neutrophils_cp17_sp17_no_lap/',
                 '../../analysis/2017_05_10_neutrophils_cp17_sp17_no_lap_smooth/')
# metadata used to define experiments
strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')


read_track_results <- function(dir_list, strata) {
  suppressMessages(read_csv(file.path(dir_list, csv_file_name))) %>% 
  group_by_(.dots = strata)
}

assess_quality <- function(track, strata){
  quality <- cytominer::assess(track, 20, strata)
  quality[is.na(quality)] <- 0
  return(quality)
  }

tracks <- lapply(dir_list, read_track_results, strata = strata)
track_quality <- lapply(tracks, assess_quality, strata = strata)
```

```{r}
track_quality[[3]] %<>% 
  mutate(Metadata = paste(Metadata_condition, Metadata_dose, Metadata_id, Metadata_date)) %>%
  mutate(Metadata_track_method = 'overlap smooth')

track_quality[[2]] %<>% 
  mutate(Metadata = paste(Metadata_condition, Metadata_dose, Metadata_id, Metadata_date)) %>%
  mutate(Metadata_track_method = 'overlap') 

track_quality[[1]] %<>% 
  mutate(Metadata = paste(Metadata_condition, Metadata_dose, Metadata_id, Metadata_date)) %>%
  mutate(Metadata_track_method = 'lap') 

common_data <- intersect(track_quality[[3]] %>% select(Metadata),
                         track_quality[[2]] %>% select(Metadata))


df <- left_join(track_quality[[3]], track_quality[[1]], by = strata, suffix = c('_overlap_smooth', '_overlap'))

ggplot(data = df, aes(x = VOT_overlap, y = VOT_overlap_smooth, color = Metadata_condition)) +
  geom_point() +
  coord_fixed()

ggplot(data = df, aes(x = Exp_Valid_Tracks_overlap, y = Exp_Valid_Tracks_overlap_smooth, color = Metadata_condition)) +
  geom_point() +
  coord_fixed()

ggplot(data = df, aes(x = sum_track_overlap, y = sum_track_overlap_smooth, color = Metadata_condition)) +
  geom_point() +
  coord_fixed()

```

# Selecting the worst data points
```{r}
track_quality[[3]] %>% 
  arrange(VOT,desc(Exp_Tracks)) %>% 
  print

```

# direct compare lap and overlap tracking
```{r}
tracks <- lapply(dir_list, read_track_results, strata = c('Metadata_condition'))
track_quality <- lapply(tracks, assess_quality, strata = c('Metadata_condition')) 

track_quality[[3]] %>%
  print()
```