---
title: "load_data"
author: "TB"
date: "5/15/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library("magrittr")
library("knitr")
library("destiny")
library("scatterplot3d")
library("car")
```


# Load data 
The output of the MATLAB tracking is stored in "track.csv", see create_metadata.Rmd
```{r}
csv_in <- 'normalized.csv'
data_dir <- '../../analysis/2017_04_28_matlab/'

strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')

normalized <- read_csv(file.path(data_dir, csv_in)) %>%
  select(Metadata_id,Metadata_matrix, Metadata_condition, Metadata_dose, everything() ) %>%
  arrange(Metadata_id, Metadata_matrix, Metadata_condition, Metadata_dose) %>%
  group_by_(.dots = strata) 
```


Visualize data using diffusion maps
```{r}

feature = c("Track_Speed","Track_Speed_Y","Track_Speed_X","Track_xFMI","Track_yFMI","Track_Directionality","Track_Distance_Traveled","Track_CI","Track_Angle")

hem <- normalized %>% 
  ungroup() %>% 
  filter(Metadata_matrix == 'HEM')

fn <- normalized %>% 
  ungroup() %>% 
  filter(Metadata_matrix == 'FN')

dif_hem <- DiffusionMap(hem, k = 50, vars = feature)
dif_fn <- DiffusionMap(fn, k = 50, vars = feature)

```

3D Plot
```{r}
scatter3d(x = dif_hem$DC1, y = dif_hem$DC2, z = dif_hem$DC3, point.col = "blue", surface=FALSE, grid = FALSE, groups = factor( dif_hem$Metadata_condition ))
```

2D Plot
```{r}
ggplot(data = dif_hem, aes(x = DC1, y = DC3, color = factor(Metadata_condition))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')
  

ggplot(data = dif_hem, aes(x = DC1, y = DC3, color = factor(Metadata_id))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')

ggplot(data = dif_hem, aes(x = DC1, y = DC2, color = factor(Metadata_condition))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')

ggplot(data = dif_hem, aes(x = DC1, y = DC2, color = factor(Metadata_id))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')


```

3D Plot
```{r}
scatter3d(x = dif_fn$DC1, y = dif_fn$DC2, z = dif_fn$DC3, point.col = "blue", surface=FALSE, grid = FALSE, groups = factor( dif_fn$Metadata_condition ))
```


2D Plot
```{r}
ggplot(data = dif_fn, aes(x = DC1, y = DC3, color = factor(Metadata_condition))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')
  

ggplot(data = dif_fn, aes(x = DC1, y = DC3, color = factor(Metadata_id))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')

ggplot(data = dif_fn, aes(x = DC1, y = DC2, color = factor(Metadata_condition))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')

ggplot(data = dif_fn, aes(x = DC1, y = DC2, color = factor(Metadata_id))) +
  geom_point() + 
  labs(title = 'DM for migration in HEM')


```
