---
title: "load_data"
author: "TB"
date: "5/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library('magrittr')
# load cytominer 

```

# Load tracking data 
```{r}
# define file name and result folder for tracked experiments
csv_file_name <- 'tracks.csv'
dir_list <- list('../../analysis/2017_06_05_tracking/','../../analysis/2017_04_28_matlab/')
# metadata used to define experiments
strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')

read_track_results <- function(dir_list, strata) {
  suppressMessages(read_csv(file.path(dir_list, csv_file_name))) %>% 
  group_by_(.dots = strata)
}
```

assess the tracking quality using cytominer::assess
```{r}
assess_quality <- function(track, strata){
  quality <- cytominer::assess(track, 20, strata)
  quality[is.na(quality)] <- 0
  return(quality)
  }

tracks <- lapply(dir_list, read_track_results, strata = strata) 

quality_list <- lapply(tracks, assess_quality, strata = strata)

quality_list[[1]] %<>% 
  mutate(algorithm = 'CellProfiler') %>% 
  mutate(Metadata_id = tolower(Metadata_id))

quality_list[[2]] %<>% 
  mutate(algorithm = 'MATLAB')

quality2 <- do.call(rbind, quality_list)
pulation <- do.call(rbind, lapply(population,data.frame))

quality <- left_join(quality_list[[2]], quality_list[[1]], 
    by = c("Metadata_condition","Metadata_dose","Metadata_id","Metadata_date","Metadata_matrix"),
    suffix = c("_matlab", "_cellprofiler"))



```


# All experiments are ordered by theri VOT
```{r}
ggplot(data=quality, aes(x = VOT_matlab, y = VOT_cellprofiler)) +
  geom_point() +
  coord_fixed() +
  xlim(0,1) +
  ylim(0,1)
```
```{r}
ggplot(data=quality, aes(x = VOT_matlab, y = Exp_Mean_Track_Life_Time_matlab)) +
  geom_point() +
  coord_fixed() +
  xlim(0,1) +
  ylim(0,1)
```

```{r}
quality %>% 
  ungroup() %>%
  group_by(Metadata_id) %>%
  summarise(vot_ml = mean(VOT_matlab),
            vot_cp = mean(VOT_cellprofiler),
            track_length_ml = mean(Exp_Mean_Track_Life_Time_matlab),
            track_length_cp = mean(Exp_Mean_Track_Life_Time_cellprofiler)) %>% 
  arrange(vot_ml) %>%
  print
```
```{r}
quality %>% 
  ungroup() %>%
  group_by(Metadata_condition) %>%
  summarise(mean_vot = mean(VOT)) %>% 
  arrange(mean_vot) %>%
  print
```