---
title: "tsne_test"
author: "TB"
date: "6/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library("magrittr")
library("knitr")
library("corrplot")
source("windrose.r")


```

```{r}
## calling the installed package
train<- read.csv(file.choose()) ## Choose the train.csv file downloaded from the link above  
library(Rtsne)
## Curating the database for analysis with both t-SNE and PCA
Labels<-train$label
train$label<-as.factor(train$label)

## Executing the algorithm on curated data
tsne <- Rtsne(train[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500)
exeTimeTsne<- system.time(Rtsne(train[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500))

## Plotting
df_tsne <- as.data.frame(tsne$Y)
df_tsne <- cbind(df_tsne, Labels)

## plotting the results without clustering
ggplot(df_tsne, aes(x = V1, y = V2, color = factor(Labels))) +  
  geom_point(size = 0.25) +
  xlab("") + ylab("") +
  ggtitle("t-SNE") +
  guides(colour = guide_legend(override.aes = list(size = 6))) +
  theme_light(base_size=20) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank()) 

  scale_colour_brewer(palette = "Set2")
```
