---
title: "load_data"
author: "TB"
date: "5/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library("magrittr")
library("knitr")
library("corrplot")
#library("cytominer")
# load cytominer 

```

# Load data 
The output of CellProfiler track module is loaded as CSV, tracked using cytominer::track and 
stored in the data folder as "track.csv". Once the data is stored, the processing is not repeated;
instead "tracks.csv" is loaded. 
```{r}
csv_in <- 'TrackeddetectedNeutros.csv'
csv_out <- 'tracks.csv'
data_dir <- '../../analysis/2017_04_28_matlab/'
strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')

if (file.exists(file.path(data_dir, csv_out))) {
  tracks <- read_csv(file.path(data_dir, csv_out))
} else {

  df <- read_csv(file.path(data_dir, csv_in))
  df %<>% dplyr::mutate(Metadata_frame = as.double(Metadata_timePoint)) 
  

  #The data contains tracking data for neutrophils from different conditions. The datasets 
  #can be ditinguished using the Metadata columns defined in strata. 
  track_label = c('TrackObjects_Label')
  
  tracks <- df %>% 
    group_by_(.dots =  c(strata,track_label)) %>%
    arrange(Metadata_timePoint) %>%
    cytominer::track(., c(strata,track_label)) %>%
    group_by_(.dots = strata) 
  }
```
## set nan values to 'None' and store the data
```{r}
tracks$Metadata_dose[is.na(tracks$Metadata_dose)] <- 'None'
write_csv(tracks, file.path(data_dir, csv_out))
```



