---
title: "load_skopy_feature"
author: "TB"
date: "5/25/2017"
output: html_document
---

```{r setup, include=FALSE}
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("ggfortify")
library("cluster")
library("magrittr")
library("reshape2")
library("corrplot")
library("outliers")
library("rbenchmark")
library("robustbase")
library("DBI")
```

# define name to skopy sqlite file and load db
```{r}
## specify sqlite file 
backend_path <- '/Users/tbecker/Documents/2017_05_22_neutros_sp/workspace/analysis/2014_07_08/measurements.sqlite'

## create db connection 
db <- src_sqlite(path = backend_path)

## table names used by skopy
tbl_name <- list( "boxes", "correlations", "descriptions", "images", "instances", "intensities", "moments", "shapes")

## function to read all tables using lapply
db2table <- function(tbl_name,db){
  tbl(db,tbl_name) %>% collect( n = Inf)
}

## collect data
skopy_db <- lapply(tbl_name, FUN = db2table, db = db) 
```

# Change ID 
the id of each image is stored as UUID in raw data format. We translate it to something usefull. 
```{r}
cast.type <- function(x) {
  paste(as.character(unlist(x)), collapse = '')
}

cast.type <- Vectorize(cast.type)

for (i in 1:8) {
 skopy_db[[i]]  %<>%
    mutate(id = cast.type(id)) 
}
```

# 
```{r}
 
moments <- skopy_db[[7]] %>%
  as.data.frame %>%
  mutate(instance_id = cast.type(instance_id)) %>%
  mutate(feature = paste(description,p,q,weighted,sep = "_")) %>%
  select(instance_id, feature, y) %>%
  rename(id = instance_id)

moments %>% print

moments %<>%  
  reshape(., idvar = "id", timevar = "feature", direction = "wide") %>% 
  print() 

```



```{r}
full_db <- c()
full_db <- left_join(skopy_db[[1]],skopy_db[[5]],by = 'id')
full_db <- left_join(full_db, skopy_db[[6]],by = 'id')
full_db <- left_join(full_db, skopy_db[[8]],by = 'id')
full_db <- left_join(full_db, moments, by = 'id')
```

How many different observation do we have?
```{r}
population %>% 
  ungroup() %>%
  group_by(instance_id) %>%
  summarise(n = n()) %>%
  summarize(number_objects = n(), features = mean(n))
```
 
how many different features do?
```{r}
df1 %>% 
  ungroup() %>%
  group_by(feature) %>% 
  summarise(n = n())
```

