---
title: "roseplot"
author: "TB"
date: "6/5/2017"
output: html_document
---

```{r setup, include=FALSE}
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library("magrittr")
library("reshape2")
library("corrplot")

```

# Load tracking data 
```{r}
csv_file_name <- 'tracks.csv'
dir_list <- list('../../analysis/2017_05_10_neutrophils_cp17_sp17_no_lap_smooth/')

# metadata used to define experiments
strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')

read_track_results <- function(dir_list, strata) {
  suppressMessages(read_csv(file.path(dir_list, csv_file_name))) %>% 
  group_by_(.dots = strata)
}

assess_quality <- function(track, strata){
  quality <- cytominer::assess(track, 20, strata)
  quality[is.na(quality)] <- 0
  return(quality)
  }

tracks <- lapply(dir_list, read_track_results, strata = strata)
track_quality <- lapply(tracks, assess_quality, strata = strata)
```