---
title: "load_data"
author: "TB"
date: "5/15/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tibble")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("purrr")
library("broom")
library("dplyr")
library("tsne")
library("ggfortify")
library("cluster")
library("magrittr")
library("knitr")
library("corrplot")
library("Rtsne")
```

# Load data 
The output of the MATLAB tracking is stored in "track.csv", see create_metadata.Rmd
```{r}
csv_in <- 'clean_normalized.csv'
data_dir <- '../../../analysis/2017_04_28_matlab/'
strata <- c('Metadata_condition','Metadata_dose','Metadata_id','Metadata_date','Metadata_matrix')

normalized <- read_csv(file.path(data_dir, csv_in)) %>%
  select(Metadata_id,Metadata_matrix, Metadata_condition, Metadata_dose, everything() ) %>%
  arrange(Metadata_id, Metadata_matrix, Metadata_condition, Metadata_dose) %>%
  group_by_(.dots = strata) 
```


Visualize data using tsne and pca
```{r}
feature_tsne = c("Track_Speed", "Track_Speed_Y", "Track_Speed_X", "Track_xFMI", "Track_yFMI",
                 "Track_Directionality", "Track_Distance_Traveled", "Track_CI", "Track_Angle")

calculate_tsnes <- function(perplexity,data) {
  return(Rtsne(data, perplexity = perplexity, verbose = TRUE, max_iter = 500, theta = 0.5, pca_scale = TRUE))
}

perplexities <- c(2,5,10,25,50,100,200,400)

HEM <- normalized %>% filter(Metadata_matrix == "HEM")
HEM_train <- HEM %>% ungroup() %>% select_(.dots = feature_tsne)
tsnes_hem <- lapply(perplexities, calculate_tsnes, data = HEM_train)

FN <- normalized %>% filter(Metadata_matrix == "FN")
FN_train <- FN %>% ungroup() %>% select_(.dots = feature_tsne)
tsnes_fn <- lapply(perplexities, calculate_tsnes, data = FN_train)

saveRDS(tsnes_hem,file.path(data_dir,'tsnes_hem.rds'))
saveRDS(tsnes_fn,file.path(data_dir,'tsnes_fn.rds'))
```

```{r}
for (i in 1:8){
  Y <- as.data.frame(tsnes_fn[[i]]$Y)

  df = cbind(as.data.frame(Y),
             as.data.frame(FN))

  print(ggplot(data = df, aes(x = V1, y = V2, color = factor(Track_Sector), shape = Metadata_condition)) +
      geom_point() +
      xlab("") + 
      ylab("") +
      ggtitle("t-SNE") +
      guides(colour = guide_legend(override.aes = list(size = 6))) +
      theme_light(base_size = 20) +
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank()) + 
      labs(title = sprintf('Migration in FN,  perplexity %f', tsnes_fn[[i]]$perplexity )))
}
```


```{r}

 
for (i in 1:8){
  Y <- as.data.frame(tsnes_fn[[i]]$Y)

  df = cbind(as.data.frame(Y),
             as.data.frame(FN))

  print(ggplot(data = df, aes(x = V1, y = V2, color = factor(Metadata_id), shape = Metadata_condition)) +
      geom_point() +
      xlab("") + 
      ylab("") +
      ggtitle("t-SNE") +
      guides(colour = guide_legend(override.aes = list(size = 6))) +
      theme_light(base_size = 20) +
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank()) + 
      labs(title = sprintf('Migration in FN,  perplexity %f', tsnes_fn[[i]]$perplexity )))
}
```



```{r}
for (i in 1:8){
  Y <- as.data.frame(tsnes_hem[[i]]$Y)

  df = cbind(as.data.frame(Y),
             as.data.frame(HEM))

  print(ggplot(data = df, aes(x = V1, y = V2, color = factor(Track_Sector), shape = Metadata_condition)) +
      geom_point() +
      xlab("") + 
      ylab("") +
      ggtitle("t-SNE") +
      guides(colour = guide_legend(override.aes = list(size = 6))) +
      theme_light(base_size = 20) +
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank()) + 
      labs(title = sprintf('Migration in HEM,  perplexity %f', tsnes_hem[[i]]$perplexity )))
}
```

```{r}
for (i in 1:8){
  Y <- as.data.frame(tsnes_hem[[i]]$Y)

  df = cbind(as.data.frame(Y),
             as.data.frame(HEM))

  print(ggplot(data = df, aes(x = V1, y = V2, color = factor(Metadata_condition), shape = Metadata_id)) +
      geom_point() +
      xlab("") + 
      ylab("") +
      ggtitle("t-SNE") +
      guides(colour = guide_legend(override.aes = list(size = 6))) +
      theme_light(base_size = 20) +
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank()) + 
      labs(title = sprintf('Migration in HEM,  perplexity %f', tsnes_hem[[i]]$perplexity )))
}
```
